'use client';
import {useEffect,useState} from 'react';

type Status='DRAFT'|'PUBLISHED';
type Post={id:number;slug:string;title:string;excerpt:string;contentMarkdown:string;authorName:string;status:Status;coverKind:string|null;publishedAt:string|null;updatedAt:string};
type Draft={slug:string;title:string;excerpt:string;contentMarkdown:string;authorName:string;status:Status;coverKind:string};
const empty:Draft={slug:'',title:'',excerpt:'',contentMarkdown:'',authorName:'194.194 Cult',status:'DRAFT',coverKind:'journal'};

export default function BlogAdmin(){
  const [token,setToken]=useState('');const [posts,setPosts]=useState<Post[]>([]);const [selected,setSelected]=useState<string>('');const [draft,setDraft]=useState<Draft>(empty);const [notice,setNotice]=useState('Enter ADMIN_TOKEN to load the CMS.');const [busy,setBusy]=useState(false);
  useEffect(()=>{const saved=sessionStorage.getItem('cultAdminToken');if(saved)setToken(saved)},[]);
  const headers=()=>({'content-type':'application/json','authorization':`Bearer ${token}`});
  const load=async()=>{setBusy(true);setNotice('Loading…');try{const r=await fetch('/api/admin/blog',{headers:{authorization:`Bearer ${token}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load');sessionStorage.setItem('cultAdminToken',token);setPosts(d.items||[]);setNotice(`${(d.items||[]).length} posts loaded.`)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const select=(post:Post)=>{setSelected(post.slug);setDraft({slug:post.slug,title:post.title,excerpt:post.excerpt,contentMarkdown:post.contentMarkdown,authorName:post.authorName,status:post.status,coverKind:post.coverKind||'journal'})};
  const fresh=()=>{setSelected('');setDraft(empty);setNotice('New draft.')};
  const save=async()=>{if(!draft.title.trim())return setNotice('Title is required.');setBusy(true);setNotice('Saving…');try{const url=selected?`/api/admin/blog/${encodeURIComponent(selected)}`:'/api/admin/blog';const r=await fetch(url,{method:selected?'PATCH':'POST',headers:headers(),body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save');setSelected(d.post.slug);setDraft({slug:d.post.slug,title:d.post.title,excerpt:d.post.excerpt,contentMarkdown:d.post.contentMarkdown,authorName:d.post.authorName,status:d.post.status,coverKind:d.post.coverKind||'journal'});setNotice(`Saved ${d.post.status.toLowerCase()} post.`);await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const remove=async()=>{if(!selected)return;if(!window.confirm(`Delete “${draft.title}”?`))return;setBusy(true);try{const r=await fetch(`/api/admin/blog/${encodeURIComponent(selected)}`,{method:'DELETE',headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to delete');fresh();await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  return <main className="blogAdmin"><div className="adminTop"><div><div className="blogEyebrow">194.194 CULT · CMS</div><h1>Blog Editor</h1><div className="adminNotice">{notice}</div></div><div className="adminToken"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="ADMIN_TOKEN"/><button onClick={load} disabled={busy}>LOAD CMS</button></div></div>
    <div className="adminGrid"><aside className="adminList"><button onClick={fresh}>＋ NEW POST</button>{posts.map(p=><button key={p.slug} className={selected===p.slug?'active':''} onClick={()=>select(p)}><b>{p.title}</b><small>{p.status} · /blog/{p.slug}</small></button>)}</aside>
      <section className="adminEditor"><label>TITLE<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>SLUG<input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} placeholder="auto-generated from title if blank"/></label><label>EXCERPT<textarea style={{minHeight:90}} value={draft.excerpt} onChange={e=>setDraft({...draft,excerpt:e.target.value})}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>AUTHOR<input value={draft.authorName} onChange={e=>setDraft({...draft,authorName:e.target.value})}/></label><label>STATUS<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label></div><label>COVER KIND<select value={draft.coverKind} onChange={e=>setDraft({...draft,coverKind:e.target.value})}><option value="journal">Journal</option><option value="caffeine">Caffeine / 194.194</option><option value="coffee-guide">Coffee Guide</option></select></label><label>CONTENT · MARKDOWN<textarea value={draft.contentMarkdown} onChange={e=>setDraft({...draft,contentMarkdown:e.target.value})} placeholder={'## Heading\n\nParagraph with **bold** text.\n\n- list item\n\n[[caffeine-structure]]\n[[coffee:espresso]]'}/></label><div className="adminActions"><button onClick={save} disabled={busy}>{selected?'SAVE CHANGES':'CREATE POST'}</button>{selected&&<a className="clearFilters" style={{display:'inline-flex',alignItems:'center'}} href={`/blog/${draft.slug}`} target="_blank" rel="noreferrer">PREVIEW ↗</a>}{selected&&<button className="danger" onClick={remove} disabled={busy}>DELETE</button>}</div></section>
    </div></main>;
}
