import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {states,slug,stateBySlug,districtsForState,pinsForDistrict} from '../../../lib/directory';
const SITE='https://cult.pincode.cafe';
export const dynamicParams=false;
export function generateStaticParams(){return states().map(state=>({state:slug(state)}))}
export function generateMetadata({params}:{params:{state:string}}):Metadata{const state=stateBySlug(params.state);if(!state)return {robots:{index:false,follow:false}};return {title:`${state} PIN Codes — District Directory | 194.194 Cult`,description:`Browse PIN codes and post offices across districts in ${state}. Check 194.194 Cult status for each PIN.`,alternates:{canonical:`${SITE}/pincodes/${params.state}`}}}
export default function StatePage({params}:{params:{state:string}}){const state=stateBySlug(params.state);if(!state)notFound();const districts=districtsForState(params.state);return <main><nav><Link href="/" className="brand"><b>194.194</b><span>CULT</span></Link><Link href="/pincodes" className="back">← ALL STATES</Link></nav><div className="breadcrumbs"><Link href="/pincodes">India</Link> / {state}</div><section className="directoryHero"><span>STATE / UT</span><h1>{state}<br/><i>PIN Codes</i></h1><p>Choose a district to browse valid PIN codes and their post offices.</p></section><section className="directoryGrid">{districts.map(d=>{const ds=slug(d),pins=pinsForDistrict(params.state,ds);return <Link key={ds} href={`/pincodes/${params.state}/${ds}`} className="directoryCard"><small>DISTRICT</small><h2>{d}</h2><p>{pins.length} PIN{pins.length===1?'':'s'}</p><b>VIEW PIN CODES →</b></Link>})}</section><footer><b>194.194 CULT</b><span>{state.toUpperCase()} PIN DIRECTORY</span><span>PIN DATA: INDIA POST / OGD</span></footer></main>}
