'use client';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';
import {pincodes} from '../lib/pincodes';

export default function Home(){const [pin,setPin]=useState('');const router=useRouter();const submit=(e:FormEvent)=>{e.preventDefault();if(/^\d{6}$/.test(pin))router.push(`/pincode/${pin}`)};return <main>
<nav><div className="brand"><b>194.194</b><span>CULT</span></div><a className="cafeBrand" href="https://pincode.cafe" target="_blank" rel="noreferrer"><img src="https://pincode.cafe/pin-code-cafe-logo.jpg" alt="Pin Code Café"/><span>FOUNDED AT<br/><b>PIN CODE CAFÉ</b></span></a></nav>
<section className="hero"><div className="eyebrow">PIN CODE · DIGIPIN · COMMUNITY</div><h1>Know your PIN.<br/><i>Find your place.</i><br/>Find your people.</h1><p>Search an Indian PIN code to understand its postal identity, discover precise-location DIGIPIN, and see whether 194.194 Cult is active there.</p>
<form onSubmit={submit}><input aria-label="PIN code" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="Enter 6-digit PIN"/><button>EXPLORE PIN →</button></form><small>Try the founding PIN: <button className="link" onClick={()=>router.push('/pincode/759001')}>759001</button></small></section>
<section className="identityGrid"><article><span>01 · POSTAL</span><h2>PIN CODE</h2><p>Your postal geography: post office, district and state.</p></article><article><span>02 · PRECISE</span><h2>DIGIPIN</h2><p>India Post&apos;s digital addressing layer for precise locations inside a PIN.</p></article><article><span>03 · PEOPLE</span><h2>194.194 CULT</h2><p>The community layer: Active, Forming, or Not Here Yet.</p></article></section>
<section className="registry"><div><span className="kicker">THE REGISTRY</span><h2>India, PIN by PIN.</h2></div><div className="stats"><b>{pincodes.filter(x=>x.status==='ACTIVE').length}</b><span>ACTIVE CULT</span><b>{pincodes.filter(x=>x.status==='FORMING').length}</b><span>FORMING</span></div></section>
<section className="origin"><span>WHERE IT STARTED</span><div><h2>PIN CODE CAFÉ</h2><p>Dhenkanal · 759001</p></div><a href="https://pincode.cafe" target="_blank" rel="noreferrer">VISIT PINCODE.CAFE →</a></section>
<footer><b>194.194 CULT</b><span>EVERY PIN HAS AN ADDRESS · EVERY PLACE CAN HAVE A DIGIPIN · SOME PINS HAVE A CULT</span><span>FOUNDED IN DHENKANAL</span></footer></main>}