import {getDb,hasDatabase} from './db';

export type BlogStatus='DRAFT'|'PENDING'|'PUBLISHED'|'REJECTED';
export type BlogPost={id:number;slug:string;title:string;excerpt:string;contentMarkdown:string;authorName:string;authorEmail:string|null;status:BlogStatus;coverKind:string|null;publishedAt:string|null;createdAt:string;updatedAt:string};
const mapPost=(r:any):BlogPost=>({id:Number(r.id),slug:r.slug,title:r.title,excerpt:r.excerpt||'',contentMarkdown:r.content_markdown||'',authorName:r.author_name||'194.194 Cult',authorEmail:r.author_email||null,status:r.status,coverKind:r.cover_kind||null,publishedAt:r.published_at?new Date(r.published_at).toISOString():null,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()});
export const blogSlug=(value:string)=>value.toLowerCase().trim().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120);
export async function listPublishedPosts(limit=50):Promise<BlogPost[]>{if(!hasDatabase())return [];const r=await getDb().query(`SELECT * FROM blog_posts WHERE status='PUBLISHED' AND (published_at IS NULL OR published_at<=NOW()) ORDER BY published_at DESC NULLS LAST,created_at DESC LIMIT $1`,[Math.min(Math.max(limit,1),100)]);return r.rows.map(mapPost)}
export async function getPublishedPost(slug:string):Promise<BlogPost|null>{if(!hasDatabase())return null;const r=await getDb().query(`SELECT * FROM blog_posts WHERE slug=$1 AND status='PUBLISHED' AND (published_at IS NULL OR published_at<=NOW()) LIMIT 1`,[slug]);return r.rowCount?mapPost(r.rows[0]):null}
export async function listAllPosts():Promise<BlogPost[]>{if(!hasDatabase())return [];const r=await getDb().query(`SELECT * FROM blog_posts ORDER BY CASE status WHEN 'PENDING' THEN 0 WHEN 'DRAFT' THEN 1 WHEN 'PUBLISHED' THEN 2 ELSE 3 END,updated_at DESC`);return r.rows.map(mapPost)}
export async function getAnyPost(slug:string):Promise<BlogPost|null>{if(!hasDatabase())return null;const r=await getDb().query(`SELECT * FROM blog_posts WHERE slug=$1 LIMIT 1`,[slug]);return r.rowCount?mapPost(r.rows[0]):null}
export async function createPost(input:{slug?:string;title:string;excerpt?:string;contentMarkdown?:string;authorName?:string;authorEmail?:string|null;status?:BlogStatus;coverKind?:string|null}){const base=blogSlug(input.slug||input.title);if(!base)throw new Error('A valid slug is required');const status=input.status||'DRAFT';let slug=base;if(status==='PENDING'){const exists=await getDb().query(`SELECT 1 FROM blog_posts WHERE slug=$1`,[slug]);if(exists.rowCount)slug=`${base}-${Date.now().toString(36)}`};const r=await getDb().query(`INSERT INTO blog_posts (slug,title,excerpt,content_markdown,author_name,author_email,status,cover_kind,published_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $7='PUBLISHED' THEN NOW() ELSE NULL END,NOW()) RETURNING *`,[slug,input.title.trim(),input.excerpt?.trim()||'',input.contentMarkdown||'',input.authorName?.trim()||'194.194 Cult',input.authorEmail?.trim()||null,status,input.coverKind||null]);return mapPost(r.rows[0])}
export async function submitCommunityPost(input:{title:string;excerpt:string;contentMarkdown:string;authorName:string;authorEmail?:string|null}){return createPost({...input,status:'PENDING',coverKind:'journal'})}
export async function updatePost(slug:string,input:Partial<{slug:string;title:string;excerpt:string;contentMarkdown:string;authorName:string;authorEmail:string|null;status:BlogStatus;coverKind:string|null}>){const current=await getAnyPost(slug);if(!current)throw new Error('Post not found');const nextSlug=blogSlug(input.slug??current.slug);if(!nextSlug)throw new Error('A valid slug is required');const nextStatus=input.status??current.status;const publishNow=nextStatus==='PUBLISHED'&&current.status!=='PUBLISHED';const r=await getDb().query(`UPDATE blog_posts SET slug=$2,title=$3,excerpt=$4,content_markdown=$5,author_name=$6,author_email=$7,status=$8,cover_kind=$9,published_at=CASE WHEN $10 THEN NOW() WHEN $8<>'PUBLISHED' THEN NULL ELSE published_at END,updated_at=NOW() WHERE slug=$1 RETURNING *`,[slug,nextSlug,(input.title??current.title).trim(),input.excerpt??current.excerpt,input.contentMarkdown??current.contentMarkdown,(input.authorName??current.authorName).trim(),input.authorEmail===undefined?current.authorEmail:input.authorEmail,nextStatus,input.coverKind===undefined?current.coverKind:input.coverKind,publishNow]);return mapPost(r.rows[0])}
export async function deletePost(slug:string){const r=await getDb().query(`DELETE FROM blog_posts WHERE slug=$1 RETURNING id`,[slug]);return Boolean(r.rowCount)}
