'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {getCachedPin} from '../../../lib/postal-store';
import type {PinRecord} from '../../../lib/directory';

export default function CachedPinDetails({pin}:{pin:string}){
  const [record,setRecord]=useState<PinRecord|null|undefined>(undefined);
  useEffect(()=>{let alive=true;getCachedPin(pin).then(r=>{if(alive)setRecord(r)}).catch(()=>{if(alive)setRecord(null)});return()=>{alive=false}},[pin]);
  if(record===undefined)return <section className="pinHero"><div className="pinNumber">{pin}</div><h1>Checking local<br/><i>postal directory</i></h1><p>Looking for postal data stored on this device.</p></section>;
  if(!record)return <><section className="pinHero"><div className="pinNumber">{pin}</div><h1>Postal data<br/><i>verification pending</i></h1><p>This six-digit PIN is not yet present in the server or local postal directory. We are not calling it invalid.</p></section><section className="pinLayers"><article><span>POSTAL IDENTITY</span><h2>PIN CODE</h2><p>Import the official All India Pincode Directory CSV on the home page to make the full postal directory available on this device.</p></article><article><span>PRECISE LOCATION</span><h2>DIGIPIN</h2><p>A PIN identifies a postal area. DIGIPIN identifies a precise location within that area.</p><a className="textCta" href="https://dac.indiapost.gov.in/mypincode/home" target="_blank" rel="noreferrer">FIND YOUR DIGIPIN AT INDIA POST →</a></article></section></>;
  return <><div className="breadcrumbs"><Link href="/pincodes">India</Link> / {record.state} / {record.district} / {record.pincode}</div><section className="pinHero"><div className="status not_here_yet"><span>●</span> NOT HERE YET</div><div className="pinNumber">{record.pincode}</div><h1>{record.district}<br/><i>{record.state}</i></h1><p>{record.postOffices.length} post office{record.postOffices.length===1?'':'s'} loaded from this device&apos;s postal directory.</p></section><section className="pinLayers"><article><span>POSTAL IDENTITY · LOCAL DIRECTORY</span><h2>PIN CODE</h2><div className="officeGrid">{record.postOffices.map(o=><article key={o.officeName}><h3>{o.officeName}</h3><p>{o.officeType||'Post Office'}{o.deliveryStatus?` · ${o.deliveryStatus}`:''}</p><small>{record.district}, {record.state} — {record.pincode}</small>{(o.divisionName||o.regionName||o.circleName)&&<small>{[o.divisionName,o.regionName,o.circleName].filter(Boolean).join(' · ')}</small>}</article>)}</div></article><article><span>PRECISE LOCATION</span><h2>DIGIPIN</h2><p>A PIN identifies a postal area. DIGIPIN identifies a precise location within that area, so one PIN can contain many DIGIPINs.</p><a className="textCta" href="https://dac.indiapost.gov.in/mypincode/home" target="_blank" rel="noreferrer">FIND YOUR DIGIPIN AT INDIA POST →</a></article></section><section className="cta"><span>194.194 CULT · {record.pincode}</span><h2>Not here yet.<br/>Be the reason it starts.</h2><button>BRING 194.194 HERE →</button></section></>;
}
