import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {findPincode} from '../../../lib/pincodes';
import {allPins,getPin,slug} from '../../../lib/directory';

const SITE='https://cult.pincode.cafe';
const label={ACTIVE:'ACTIVE',FORMING:'FORMING',NOT_HERE_YET:'NOT HERE YET'} as const;
export const dynamicParams=false;
export function generateStaticParams(){return allPins().map(x=>({pin:x.pincode}))}
export function generateMetadata({params}:{params:{pin:string}}):Metadata{const d=getPin(params.pin);if(!d)return {title:'PIN Code Not Found',robots:{index:false,follow:false}};const office=d.postOffices[0]?.officeName;const title=`${d.pincode} PIN Code — ${d.district}, ${d.state} | DIGIPIN & 194.194 Cult`;const description=`Explore ${d.pincode} PIN code for ${office||d.district}, ${d.district}, ${d.state}: post offices, DIGIPIN guidance and 194.194 Cult community status.`;return {title,description,alternates:{canonical:`${SITE}/pincode/${d.pincode}`},openGraph:{title,description,url:`${SITE}/pincode/${d.pincode}`,type:'website'}}}
export default function PinPage({params}:{params:{pin:string}}){const d=getPin(params.pin);if(!d)notFound();const cult=findPincode(params.pin);const status=cult?.status??'NOT_HERE_YET';const stateSlug=slug(d.state),districtSlug=slug(d.district);const jsonLd={"@context":"https://schema.org","@type":"PostalAddress",postalCode:d.pincode,addressLocality:d.district,addressRegion:d.state,addressCountry:'IN'};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><nav><Link href="/" className="brand"><b>194.194</b><span>CULT</span></Link><Link href="/" className="back">← SEARCH ANOTHER PIN</Link></nav><div className="breadcrumbs"><Link href="/pincodes">India</Link> / <Link href={`/pincodes/${stateSlug}`}>{d.state}</Link> / <Link href={`/pincodes/${stateSlug}/${districtSlug}`}>{d.district}</Link> / {d.pincode}</div><section className="pinHero"><div className={`status ${status.toLowerCase()}`}><span>●</span> {label[status]}</div><div className="pinNumber">{d.pincode}</div><h1>{d.district}<br/><i>{d.state}</i></h1><p>{d.postOffices.length} post office{d.postOffices.length===1?'':'s'} listed for PIN {d.pincode}.</p></section><section className="pinLayers"><article><span>POSTAL IDENTITY</span><h2>PIN CODE</h2><div className="officeGrid">{d.postOffices.map(o=><article key={o.officeName}><h3>{o.officeName}</h3><p>{o.officeType||'Post Office'}{o.deliveryStatus?` · ${o.deliveryStatus}`:''}</p><small>{d.district}, {d.state} — {d.pincode}</small></article>)}</div></article><article><span>PRECISE LOCATION</span><h2>DIGIPIN</h2><p>A PIN identifies a postal area. DIGIPIN identifies a precise location within that area, so one PIN can contain many DIGIPINs.</p><a className="textCta" href="https://dac.indiapost.gov.in/mypincode/home" target="_blank" rel="noreferrer">FIND YOUR DIGIPIN AT INDIA POST →</a></article></section>{status==='ACTIVE'?<section className="chapter"><span>194.194 CULT · CHAPTER</span><h2>{cult?.chapter}</h2>{cult?.host==='Pin Code Café'&&<a className="foundingCafe" href="https://pincode.cafe" target="_blank" rel="noreferrer"><img src="https://pincode.cafe/pin-code-cafe-logo.jpg" alt="Pin Code Café"/><div><small>BIRTHPLACE OF 194.194 CULT</small><b>Pin Code Café · Dhenkanal</b><em>pincode.cafe →</em></div></a>}<dl><div><dt>HOME</dt><dd>{cult?.host}</dd></div><div><dt>SINCE</dt><dd>{cult?.since}</dd></div><div><dt>STATUS</dt><dd>ALIVE & BREWING ☕</dd></div></dl><blockquote>“This PIN has a Cult.”</blockquote></section>:<section className="cta"><span>194.194 CULT · {d.pincode}</span><h2>Not here yet.<br/>Be the reason it starts.</h2><button>BRING 194.194 HERE →</button><p>Register interest. When enough people raise their hands, this PIN starts forming.</p></section>}<footer><b>194.194 CULT</b><span>PIN CODE · DIGIPIN · COMMUNITY</span><span>PIN DATA: INDIA POST / OGD</span></footer></main>}
