import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {states,slug,districtsForState,stateBySlug,districtBySlug,pinsForDistrict} from '../../../../lib/directory';
const SITE='https://cult.pincode.cafe';
export const dynamicParams=false;
export function generateStaticParams(){return states().flatMap(state=>{const s=slug(state);return districtsForState(s).map(d=>({state:s,district:slug(d)}))})}
export function generateMetadata({params}:{params:{state:string;district:string}}):Metadata{const state=stateBySlug(params.state),district=districtBySlug(params.state,params.district);if(!state||!district)return {robots:{index:false,follow:false}};return {title:`${district} PIN Codes, ${state} — DIGIPIN & Cult`,description:`Browse PIN codes and post offices for ${district}, ${state}. Open any PIN for postal details, DIGIPIN guidance and 194.194 Cult status.`,alternates:{canonical:`${SITE}/pincodes/${params.state}/${params.district}`}}}
export default function DistrictPage({params}:{params:{state:string;district:string}}){const state=stateBySlug(params.state),district=districtBySlug(params.state,params.district);if(!state||!district)notFound();const pins=pinsForDistrict(params.state,params.district);return <main><nav><Link href="/" className="brand"><b>194.194</b><span>CULT</span></Link><Link href={`/pincodes/${params.state}`} className="back">← {state.toUpperCase()}</Link></nav><div className="breadcrumbs"><Link href="/pincodes">India</Link> / <Link href={`/pincodes/${params.state}`}>{state}</Link> / {district}</div><section className="directoryHero"><span>DISTRICT</span><h1>{district}<br/><i>{state}</i></h1><p>{pins.length} PIN code{pins.length===1?'':'s'} in this directory.</p></section><section className="pinGrid">{pins.map(p=><Link key={p.pincode} href={`/pincode/${p.pincode}`} className="pinCard"><strong>{p.pincode}</strong><span>{p.postOffices[0]?.officeName||district}</span><small>{p.postOffices.length} post office{p.postOffices.length===1?'':'s'} · DIGIPIN · CULT</small></Link>)}</section><footer><b>194.194 CULT</b><span>{district.toUpperCase()} · {state.toUpperCase()}</span><span>PIN CODE · DIGIPIN · COMMUNITY</span></footer></main>}
